- name: Create Folder - {{ item.dir }}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: {{item.dir}}
    user: admin
    password: "{{jenkins_password}}"
    url: http://172.31.4.85:8080
  loop:
    - CIPipelines

- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - {name: "frontend", dir: "CIPipelines"}
    - {name: "cart", dir: "CIPipelines"}
    - {name: "catalogue", dir: "CIPipelines"}
    - {name: "user", dir: "CIPipelines"}
    - {name: "payment", dir: "CIPipelines"}
    - {name: "shipping", dir: "CIPipelines"}








