- name: Create config files
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job-{{item.name}}.xml

- name: Creating the Job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job-{{item.name}}.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    user: admin
    password: "{{jenkins_password}}"
    url: http://172.31.4.85:8080